### ISSUE TITLE
srec_info not installed by default on Ubuntu 14.04

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/ble-examples#7]
When compiling on Ubuntu 14.04, for the `nrf51dk-armcc` target, it uses `srec_info` from the `srecord` package, which is not installed by default.

`sudo apt-get install srecord` solves this.
- Whose responsiblity is this?
- Is this part of the build system, so the dependencies for yotta should install this?
- Or is this a dependency specific only to the nrf51dk target? 
- Should you have to manually install this if you want to use this target then? 
- Would you have to read the targets ReadMe first, or should `yotta target` inform you of that dependency?

@rgrover @autopulated

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1088

**Comment by autopulated** [comment]
it's a program that's best considered part of the compiler toolchain (like the linker, for example).

In this case we can actually use a python script instead of sec_cat. The base nordic targets do that: https://github.com/ARMmbed/target-nrf51822/blob/master/nordic-nrf51822-16k-gcc/scripts/merge_hex.py

**Comment by rgrover** [comment]
@autopulated this is 'srec_info'. it may not be trivial to implement it in python.

**Comment by autopulated** [comment]
@rgrover see edit ;)

**Comment by rgrover** [comment]
srec_info is now no longer a part of the toolchain. refer to https://github.com/ARMmbed/target-nrf51dk-armcc/issues/4
